In [1]:
import numpy as np

In [2]:
#Create Numpy Array

In [3]:
my_list = [1,2,3]

In [4]:
x = np.array(my_list)

In [5]:
type(x)

numpy.ndarray

In [6]:
my_matrix =[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [9]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [11]:
type(1)

int

In [12]:
type(1.0)

float

In [13]:
np.zeros((7,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
np.ones(1)

array([ 1.])

In [15]:
np.ones((8,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [16]:
np.linspace(0,10,30)

array([  0.        ,   0.34482759,   0.68965517,   1.03448276,
         1.37931034,   1.72413793,   2.06896552,   2.4137931 ,
         2.75862069,   3.10344828,   3.44827586,   3.79310345,
         4.13793103,   4.48275862,   4.82758621,   5.17241379,
         5.51724138,   5.86206897,   6.20689655,   6.55172414,
         6.89655172,   7.24137931,   7.5862069 ,   7.93103448,
         8.27586207,   8.62068966,   8.96551724,   9.31034483,
         9.65517241,  10.        ])

In [17]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [18]:
np.random.rand(5,5)

array([[ 0.12892452,  0.28132684,  0.8247125 ,  0.69468045,  0.35885889],
       [ 0.09466515,  0.69361763,  0.44554503,  0.61003982,  0.00368327],
       [ 0.98250521,  0.44895836,  0.68559394,  0.19117706,  0.45629739],
       [ 0.2500744 ,  0.49118001,  0.75730345,  0.85593527,  0.83212384],
       [ 0.37165851,  0.38565335,  0.41207332,  0.06018756,  0.30476328]])

In [19]:
np.random.randn(5)

array([-1.32669051,  2.61020277,  0.58461337, -1.24267995, -0.59946539])

In [20]:
np.random.randn(5,5)

array([[-0.00441927,  0.31500249,  0.35615055, -0.98843321,  1.47670058],
       [-0.90197127, -1.77348609, -1.59151217,  1.82214104,  0.23556051],
       [-0.87503158, -1.31998707, -1.55532467, -0.10938605, -1.80272823],
       [-1.30626746,  2.03634338,  0.50156947,  0.8597153 , -0.86292844],
       [ 0.3670718 ,  0.25507069, -0.81283278, -1.84001022,  0.12357383]])

In [21]:
np.random.randint(5)

4

In [22]:
np.random.randint(1,100,10)

array([92, 47, 69, 97, 33, 62, 93, 25,  6, 64])

In [23]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arr.shape

(25,)

In [26]:
arr.reshape(5,5).shape

(5, 5)

In [27]:
arr.dtype

dtype('int32')

In [28]:
ranarr.max()

43

In [29]:
ranarr.argmax()

5

In [30]:
ranarr.min()

1

    ## Numpy Operation

In [31]:
arr = np.arange(0,10)

In [32]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [35]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
arr / arr

C:\Users\avinash.t\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [37]:
1/arr

C:\Users\avinash.t\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111])

In [38]:
arr**7

array([      0,       1,     128,    2187,   16384,   78125,  279936,
        823543, 2097152, 4782969], dtype=int32)

In [39]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [40]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [42]:
arr = np.arange(0,11)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[9]

9

In [45]:
arr[1:5]

array([1, 2, 3, 4])

In [46]:
arr[0:5] = 100

In [47]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
arr = np.arange(0,11)

In [49]:
arr_copy = arr.copy()

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [53]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
mat[0]

array([ 5, 10, 15])

In [55]:
mat[1][1]

25

In [56]:
mat[1,1]

25

In [57]:
mat[0,2]

15

In [58]:
mat[:2, 1:]

array([[10, 15],
       [25, 30]])

In [60]:
mat[1:, :2]

array([[20, 25],
       [35, 40]])

In [61]:
arr = np.arange(1,11)

In [62]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [64]:
bool_array = arr > 4

In [65]:
arr[bool_array]

array([ 5,  6,  7,  8,  9, 10])

In [66]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])